name: elrond_sdk
description: Elrond SDK for Dart
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  bip39: ^1.0.4
  convert: ^2.1.1
  dio: ^3.0.10
  ed25519_hd_key: ^1.1.0
  freezed_annotation: ^0.12.0
  meta: ^1.2.4
  pedantic: ^1.9.0
  pointycastle: ^2.0.1
  retrofit: ^1.3.4+1
  tweetnacl: ^0.3.2

dev_dependencies:
  build_runner: ^1.10.11
  freezed: ^0.12.6
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1+1
  test: ^1.15.7
